version: "3.8"

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:password@db:5432/mydatabase"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: flask_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
