version: "3.8"

services:
  app:
    build: .
    container_name: news_service_app
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      NEWS_API_KEY: your_news_api_key
      OPENAI_API_KEY: your_openai_api_key
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: news_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
